name: 'Build VSIX'
description: "Build the extension's VSIX"

inputs:
  node_version:
    description: 'Version of Node to install'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Node
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: ${{ inputs.node_version }}

    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Find pnpm store
      id: pnpm-store
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: pnpm cache
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-build-vsix-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-build-vsix-

    # Minimum supported version is Python 3.11
    - name: Use Python 3.11
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        version: '0.11.23'
        enable-cache: true

    - name: Install Node dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Install bundled python libraries
      run: uv run --frozen --group dev nox --session install_bundled_libs
      shell: bash

    # Use the GITHUB_RUN_ID environment variable to update the build number.
    # GITHUB_RUN_ID is a unique number for each run within a repository.
    # This number does not change if you re-run the workflow run.
    - name: Update extension build number
      run: uv run --frozen --group dev nox --session update_build_number -- $GITHUB_RUN_ID
      shell: bash

    - name: Build VSIX
      run: pnpm run vsce-package
      shell: bash

    - name: Upload VSIX
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: formatter-package
        path: |
          **/*.vsix
        if-no-files-found: error
        retention-days: 7
