name: 'Lint'
description: 'Lint TypeScript and Python code'

inputs:
  node_version:
    description: 'Version of Node to install'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Node
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version: ${{ inputs.node_version }}

    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Find pnpm store
      id: pnpm-store
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: pnpm cache
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
      with:
        path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-lint-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-lint-

    - name: Install Node dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Lint TypeScript code
      run: pnpm run lint
      shell: bash

    - name: Check TypeScript format
      run: pnpm run format-check
      shell: bash

    - name: Install Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        version: '0.11.33'
        enable-cache: true

    # This will install libraries to a target directory.
    - name: Install bundled python libraries
      run: uv run --frozen --group dev nox --session install_bundled_libs
      shell: bash

    - name: Check linting and formatting
      run: uv run --frozen --group dev nox --session lint
      shell: bash
