name: PR Validation

on:
  pull_request:

permissions:
  contents: read

env:
  NODE_VERSION: 22
  TEST_RESULTS_DIRECTORY: .
  # Force a path with spaces and unicode chars to test extension works in these scenarios
  special-working-directory: './🐍 🐛'
  special-working-directory-relative: '🐍 🐛'
  DISABLE_TRANSLATIONS: true

jobs:
  build-vsix:
    name: Create VSIX
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Build VSIX
        uses: ./.github/actions/build-vsix
        with:
          node_version: ${{ env.NODE_VERSION}}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Lint
        uses: ./.github/actions/lint
        with:
          node_version: ${{ env.NODE_VERSION }}

  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ env.special-working-directory }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ['3.11', '3.12', '3.13', '3.14']

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          path: ${{ env.special-working-directory-relative }}

      # Install bundled libs using 3.11 even though you test it on other versions.
      - name: Use Python 3.11
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: '0.11.23'
          enable-cache: true

      # This will install libraries to a target directory.
      - name: Install bundled python libraries
        run: uv run --frozen --group dev nox --session install_bundled_libs
        shell: bash

      # Now that the bundle is installed to target using python 3.11
      # switch back the python we want to test with
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python }}

      - name: Run tests
        run: uv run --frozen --python ${{ matrix.python }} --group dev nox --session tests
        shell: bash

      - name: Validate README.md
        run: uv run --frozen --python ${{ matrix.python }} --group dev nox --session validate_readme
        shell: bash
